# Set to true to add reviewers to pull requests
addReviewers: true

# A list of assignees, overrides reviewers if set
reviewers:
  - aishayusuff

numberOfReviewers: 0

# Set to true to add assignees to pull requests
addAssignees: author
