name: Auto Assign
on:
  pull_request:
    types: [opened, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.AUTO_ASSIGN }}
          reviewers: |
            aishayusuff
          assignees: author
